#!/bin/bash

# run code

 num_jobs=10
 i=1
 let imax=$i+&num_jobs

#loop
 wile [ $i -lt $imax ]; do
    
       echo $i
  
       export ftn20=E_AAcY_1.run$i.dat
       cat Dmeson_AAcY_1.run$i.dat |./radiation

       let i=$i+1
 done
